---
title: "InsertionExpressionEffects.Rmd"
author: "bhaas"
date: '2023-04-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}

insertions_data = read.table("../InsertionAnalysis/all_insertions_and_virus_content_merged.FILTERED.tsv", header=T, sep="\t", stringsAsFactors = F)

insertions_data = insertions_data %>% select(sample_id, contig, humanchr, human_coord, total, total_rpm)


```


```{r}

insertions_w_expression_data = read.table("virus_insertions_unfiltered.10kb.expression_region_analysis.tsv", header=T, sep="\t", stringsAsFactors = F)

insertions_w_expression_data = insertions_w_expression_data %>% filter(cohort=="TCGA")

#insertions_w_expression_data = insertions_w_expression_data %>% filter(cohort=="GTEx")

```

```{r}

insertions_w_expression_data = inner_join(insertions_w_expression_data, 
                                         insertions_data %>% select(-humanchr),
                                         by=c('sample_id', 'contig'))

```

```{r}

BINSIZE=1000000

nrow(insertions_w_expression_data)

insertions_w_expression_data = insertions_w_expression_data %>% mutate(bin = paste0(chrom, "^", round(human_coord / BINSIZE))) %>% group_by(sample_id, bin) %>% arrange(desc(total_rpm)) %>% filter(row_number()==1) %>% ungroup()

nrow(insertions_w_expression_data)
```


```{r}

plot(density(insertions_w_expression_data$expr_quantile))

```


# examine the randomized data:

```{r}

randomized_data = read.table("virus_insertions_unfiltered.10kb.expression_region_analysis.RANDOMIZED.tsv", header=T, sep="\t", stringsAsFactors = F)

nrow(randomized_data)

randomized_data = inner_join(insertions_w_expression_data %>% select(sample_id, contig, total, total_rpm),
                            randomized_data,
                            by=c('sample_id', 'contig'))
nrow(randomized_data)

```

```{r}


plot(density(randomized_data$expr_quantile))


```

```{r}

# combine them

plot(density(insertions_w_expression_data$expr_quantile))

points(density(randomized_data$expr_quantile), col='red', t='l')



```



```{r}

p = insertions_w_expression_data %>% ggplot(aes(x=expr_quantile)) + geom_density( fill='blue', alpha=0.5)

p = p + geom_density(data=randomized_data, fill='yellow', alpha=0.5, )

p



```



```{r}

hist( insertions_w_expression_data$expr_quantile)

hist(randomized_data$expr_quantile)



```




# examine at virus level

```{r}

combined_data = bind_rows(insertions_w_expression_data %>% mutate(type='real'),
                          randomized_data %>% mutate(type='random_loc') )


```


# summarize for those viruses with min 3 insertions.

```{r}

viruses_min_3_sample_insertions = combined_data %>% filter(type=='real') %>% select(sample_id, virus) %>% group_by(virus) %>% tally() %>% filter(n>=3) %>% pull(virus)

viruses_min_3_sample_insertions

```


```{r}

combined_data = combined_data %>% filter(virus %in% viruses_min_3_sample_insertions)

```


```{r}


combined_data %>% ggplot(aes(x=virus, y=expr_quantile, fill=type)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


```




```{r}
# run statistics

viruses = combined_data %>% select(virus) %>% unique() %>% pull(virus)

stats_df = NULL

for (virus_name in viruses) {
  message(virus_name)
  virus_data = combined_data %>% filter(virus == virus_name)
  real_insertions_expr_quantiles = virus_data %>% filter(type=='real') %>% pull(expr_quantile)
  random_loc_expr_quantiles = virus_data %>% filter(type=='random_loc') %>% pull(expr_quantile)
  
  if (length(real_insertions_expr_quantiles) >= 3 & length(random_loc_expr_quantiles >= 3)) {
     w = wilcox.test(real_insertions_expr_quantiles, random_loc_expr_quantiles, alternative='greater')
  
     #message(virus_name)
     #print(w)
  
    stats_df = bind_rows(stats_df, data.frame(virus=virus_name, p_raw = w$p.value))
   }
}

stats_df$p_bh = p.adjust(stats_df$p, method='hochberg')

stats_df %>% arrange(p_bh)

```



