---
title: "virus content and insertions analysis"
author: "Brian Haas"
date: "2/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)

```

```{r}

MIN_CHIM_READS = 10
MIN_MAPPED_READS = 1000
MIN_N_BASES_COVERED = 300

```


```{r}

gtex_samples_info = read.table("__select_samples/gtex.samples.tsv", sep="\t", stringsAsFactors = F, header=T)

```

```{r}

gtex_samples_info = gtex_samples_info %>% select(entity.sample_id, tissue_id)

```



# refined insertions data
```{r}


insertions_data = read.table(gzfile("data/refined_results.agg.tsv.gz"), sep="\t", com='', stringsAsFactors = F, header=T)

insertions_data = insertions_data %>% rename(sample_name = X.sample)
insertions_data$sample_name = str_replace(insertions_data$sample_name, ".vif.refined.tsv", "")
#insertions_data$TCGA = sapply(insertions_data$sample_name, function(x) { str_split(x, "-", n=2, simplify=FALSE)[[1]][1]} )
insertions_data = insertions_data %>% filter(total > 0)

```

```{r}

insertions_data = full_join(insertions_data, gtex_samples_info, by=c('sample_name' = 'entity.sample_id'))

```



```{r}

# assign virus column

insertions_data = insertions_data %>% 
    # restrict to insertions in the primary human chromosomes
    filter(grepl("chr", chrA) | grepl("chr", chrB)) %>%
    # assign virus and humanchr columns
    mutate(virus = ifelse(grepl("chr", chrA), chrB, chrA),
    humanchr = ifelse(grepl("chr", chrA), chrA, chrB) )

```

```{r}

# write refined insertion report

write.table(insertions_data, file="insertions.tsv", quote=F, sep="\t", row.names=F)


```

# Virus content


```{r}
virus_content_data = read.table(gzfile("data/virus_reports.agg.tsv.gz"), header=T, sep="\t", stringsAsFactors = F, com='')

virus_content_data = virus_content_data %>% rename(sample_name = X.sample)

virus_content_data$sample_name = str_replace(virus_content_data$sample_name, ".VirusDetect.virus_read_counts_summary.tsv", "")

# virus_content_data$TCGA = sapply(virus_content_data$sample_name, function(x) { str_split(x, "-", n=2, simplify=FALSE)[[1]][1]} )


```



```{r}
# examine distribution of mapped reads per sample

# first, keep simple, limit to top-most virus per sample

virus_content_data_top_only = virus_content_data %>% group_by(sample_name) %>% arrange(desc(mapped)) %>% filter(row_number() == 1) %>% ungroup()

write.table(virus_content_data_top_only, "virus_sample_content.top_only.tsv", sep="\t", row.names = F, quote=F)

```



```{r}

virus_content_data_top_only %>% ggplot(aes(y=mapped, x=TCGA)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, hjust = 1))


```

```{r}

tcga_types = virus_content_data_top_only %>% select(TCGA) %>% unique() %>% pull(TCGA)

for (tcga_type in tcga_types) {
    tcga_type_data = virus_content_data_top_only %>% filter(TCGA == tcga_type)
    p = tcga_type_data %>% ggplot(aes(x=virus, y=mapped)) + geom_boxplot() + ggtitle(tcga_type) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(0.7) ))
    plot(p)
}

```





```{r}
# initial check with CESC

virus_content_data_top_only %>% filter(TCGA == "CESC") %>% 
    filter(mapped >= MIN_MAPPED_READS & n_bases_covered >= MIN_N_BASES_COVERED) %>% count()




```


```{r}

# require at least 1000 reads



tcga_types = virus_content_data_top_only %>% select(TCGA) %>% unique() %>% pull(TCGA)

for (tcga_type in tcga_types) {
    tcga_type_data = virus_content_data %>% filter(TCGA == tcga_type) %>% 
        filter(mapped >= MIN_MAPPED_READS & n_bases_covered >= MIN_N_BASES_COVERED) 
    
    virus_counts =  tcga_type_data %>% group_by(virus) %>% tally() %>% arrange(desc(n))
    
    ordered_viruses = virus_counts %>% pull(virus)
    
    tcga_type_data$virus = factor(tcga_type_data$virus, levels=ordered_viruses)
    
    p2 = tcga_type_data %>% group_by(virus) %>% tally() %>% ggplot(aes(x=virus, y=n)) + geom_col() +
        theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
        geom_text(aes(label = n), vjust = 'center', color='orange')

    #plot(p2)
    
    p = tcga_type_data %>% ggplot(aes(x=virus, y=mapped)) + geom_boxplot() + ggtitle(tcga_type) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(0.7) ))
    #plot(p)
    
   
    
    p = plot_grid(p2, p, ncol=1, align='v', rel_heights = c(0.25, 0.75))
    plot(p)
    
    
}


```




```{r}

filtered_virus_content_data = virus_content_data %>% filter(mapped >= MIN_MAPPED_READS & n_bases_covered >= MIN_N_BASES_COVERED) 

head(filtered_virus_content_data)
```

```{r}

write.table(filtered_virus_content_data, "virus_sample_content.filtered.tsv", sep="\t", row.names = F, quote=F)


```


# integrate virus content and insertion data


```{r}

#Examine numbers of samples per tcga type

# cat */*gs.files.list | grep init | grep abridged |grep full |  perl -MFile::Basename -lane '$fname = basename($_); @pts = split(/\./, $fname); $sample = $pts[0]; @pts2 = split(/-/, $sample); $tcga = $pts2[0]; print join("\t", $tcga, $sample);' > tcga.samples_list

tcga_samples_list_file = "data/tcga.samples_list"
tcga_samples_processed = read.table(tcga_samples_list_file, header=F, sep="\t", stringsAsFactors = F)

colnames(tcga_samples_processed) = c("TCGA", "sample_name")

tcga_sample_counts = tcga_samples_processed %>% group_by(TCGA) %>% tally(name='tot_samples')

tcga_sample_counts


```

```{r}
# plot sample counts

tcga_sample_counts %>%
    ggplot(aes(x=TCGA, y=tot_samples)) + geom_bar(position='dodge', stat='identity') +
    geom_text(aes(label = tot_samples )  , vjust = 'left', color='black') +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
               



```


```{r}

# divide into tumor vs. normal

tcga_samples_processed$sample_type = sapply(tcga_samples_processed$sample_name, function(x) {str_split(x, "-")[[1]][4] })

tcga_sample_counts_by_sampletype = tcga_samples_processed %>% group_by(TCGA, sample_type) %>% tally(name='tot_samples')

tcga_sample_counts_by_sampletype %>%
    ggplot(aes(x=TCGA, y=tot_samples)) + geom_bar(position='dodge', stat='identity', aes(fill=sample_type)) +
    geom_text(aes(label = tot_samples )  , vjust = 'center', color='black') +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
               

```





```{r}

insertions_data = insertions_data %>% 
    filter(total >= MIN_CHIM_READS) %>%
    rowwise() %>% mutate(i_site = paste(virus, humanchr, sep=":"))

```

```{r}
head(insertions_data)

```


```{r}

insertions_distilled = insertions_data %>% 
    # take highest scoring i_site 
    group_by(sample_name, i_site) %>% arrange(desc(total)) %>% filter(row_number() == 1) %>% ungroup() %>%
    # add the total to the i_site
    mutate(i_site = paste(i_site, paste0("T=",total), sep="^")) %>%
    
    # summarize i_sites per sample
    group_by(sample_name) %>%
    mutate(i_sites = paste(i_site, collapse=",")) %>% 
    select(TCGA, sample_name, i_sites) %>% 
    unique()
    

```

```{r}

insertions_distilled

```

```{r}

virus_content_data = virus_content_data %>% 
    filter(mapped >= MIN_MAPPED_READS & n_bases_covered >= MIN_N_BASES_COVERED)

virus_content_data
```


```{r}

virus_content_distilled = virus_content_data %>% 
    mutate(virus_token = paste0(virus, "^Mpd=", mapped, "^Fr=", frac_covered)) %>%
    group_by(sample_name) %>% 
    arrange(desc(frac_covered)) %>%
    mutate(virus_list = paste(virus_token, collapse=',') ) %>% 
    ungroup() %>% 
    select(sample_name, TCGA, virus_list)

```


```{r}

virus_content_distilled

```


```{r}

merged_distilled_report = full_join(virus_content_distilled, insertions_distilled, by=c('sample_name', 'TCGA'))

merged_distilled_report = full_join(merged_distilled_report, tcga_samples_processed %>% 
                                        select(sample_name, sample_type), by='sample_name')

```


```{r}

merged_distilled_report


```

```{r}
merged_distilled_report %>% filter(is.na(virus_list))
```


                         
                         

```{r}

write.table(merged_distilled_report, file='tcga_subset.virus_content_and_insertions.distilled.tsv', quote=F, sep="\t", row.names=F)


```



```{r}

row_processor = function(virus_list, isite_list) {
    
    virus_list = str_split(virus_list, ",")[[1]]
    #print(virus_list)
    viruses = unique(sapply(virus_list, function(x) { str_split(x, "\\^")[[1]][1]}))
    
    #print(viruses)
    
    isite_list = str_split(isite_list, ",")[[1]]
    isite_viruses = unique(sapply(isite_list, function(x) { str_split(x, ":")[[1]][1]}))
    
    #print(isite_viruses)
    
    isite_virus_not_contained = isite_viruses[ ! isite_viruses %in% viruses]
    #isite_virus_not_contained = c(isite_viruses, viruses)
    
    #print(isite_virus_not_contained)
    
    retval = paste(isite_virus_not_contained, collapse=",")
    #print(retval)
    if (retval %in% c("", "NA") ) {
        retval = NA
    }
    
    return(retval)
    
}

```

```{r}

merged_report_w_conflicts = merged_distilled_report %>% rowwise() %>% mutate(conflict = row_processor(virus_list, i_sites)) %>% ungroup()

merged_report_w_conflicts 

```


```{r}

# pull out the conflicts

merged_report_w_conflicts %>% filter(! is.na(conflict) )


```


```{r}

# plot all insertions ranked desc(total), indicate positions of discrepancies

# first restructure the reporting for analysis

combined_data = full_join(virus_content_data, insertions_data, by=c('sample_name', 'virus', 'TCGA'), suffix=c('_vcontent', '_insertion') )

# include sample type
combined_data = full_join(combined_data, 
                          tcga_samples_processed %>% 
                                select(sample_name, sample_type), by='sample_name') 

```

```{r}
combined_with_insertions_data = combined_data %>% 
    filter(! is.na(total)) %>%
    mutate(orphan = is.na(mapped))


p = combined_with_insertions_data %>%
    mutate(row=row_number()) %>% 
    ggplot(aes(y=total, x=reorder(row, -total))) + geom_point(aes(color=orphan)) +
    scale_y_continuous(trans='log10')

plot(p)


```

```{r}

combined_with_insertions_data %>% filter(orphan) %>% select(sample_name, virus, i_site, total)


```
```{r}

# count total number of samples w/ virus

sample_counts_with_virus = combined_data %>% filter(! is.na(mapped)) %>% 
    select(TCGA, sample_name, sample_type) %>% unique() %>% 
    group_by(TCGA, sample_type) %>% tally(name='w_virus')


sample_counts_with_virus

```

```{r}

sample_counts_with_insertions =  combined_data %>% filter(! is.na(total)) %>% 
    select(TCGA, sample_type, sample_name) %>% unique() %>% group_by(TCGA, sample_type) %>% tally(name='w_inserts')


sample_counts_with_insertions
```

```{r}

summary_count_table = full_join(tcga_sample_counts_by_sampletype, sample_counts_with_virus)
summary_count_table = full_join(summary_count_table, sample_counts_with_insertions)

summary_count_table[is.na(summary_count_table)] = 0

summary_count_table
```

```{r}

summary_count_table_w_frac = summary_count_table %>% 
    mutate(frac_w_virus = w_virus/tot_samples,
           frac_w_inserts = w_inserts / tot_samples)

summary_count_table_w_frac
```
```{r}


summary_count_table_w_frac %>% gather(key=frac_type, value=fraction, frac_w_virus, frac_w_inserts) %>%
    ggplot(aes(x=sample_type, y=fraction, fill=frac_type)) + geom_bar(position='dodge', stat='identity') +
    geom_text(aes(label =  sprintf("%.2f", fraction) )  , vjust = 'left', color='black') +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    facet_wrap(~TCGA, scale='free_x')

# stick to TP and NT sample types

summary_count_table_w_frac %>% 
    filter(sample_type %in% c('TP', 'NT')) %>%
    gather(key=frac_type, value=fraction, frac_w_virus, frac_w_inserts) %>%
    ggplot(aes(x=sample_type, y=fraction, fill=frac_type)) + geom_bar(position='dodge', stat='identity') +
    geom_text(aes(label =  sprintf("%.2f", fraction) )  , vjust = 'left', color='black') +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    facet_wrap(~TCGA, scale='free_x')
```





