---
title: "examine_bmark_accuracy"
author: "bhaas"
date: '2022-12-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}

get_TP_FP_per_virus = function(file_prefix) {
    
    TP_per_virus_fname = paste0(file_prefix, ".TP_called_per_virus")
    FP_per_virus_fname = paste0(file_prefix, ".FP_per_virus")
    
    TP_per_virus = read.table(TP_per_virus_fname, header=T, sep="\t", stringsAsFactors = F) %>% rename(TP = sum_found)
    FP_per_virus = read.table(FP_per_virus_fname, header=T, sep="\t", stringsAsFactors = F) %>% rename(FP = n)
    
    TP_FP_per_virus = full_join(TP_per_virus, FP_per_virus, by=c('min_reads', 'virus'))
}


```


```{r}

ctat_vif_data = get_TP_FP_per_virus("data/ctat_vif.agg.tsv.prepped.truthset_mapped") %>% mutate(method='ctat-VIF')

ViFi_data = get_TP_FP_per_virus("data/vifi.agg.tsv.prepped.truthset_mapped") %>% mutate(method='ViFi')

batvi_data = get_TP_FP_per_virus("data/batvi.agg.tsv.prepped.truthset_mapped") %>% mutate(method='BatVI')

virusbreakend_data = get_TP_FP_per_virus("data/virusbreakend.agg.tsv.prepped.truthset_mapped") %>% mutate(method='VIRUSBreakend')

VF2Verse_data = get_TP_FP_per_virus("data/VF2Verse.agg.tsv.prepped.truthset_mapped") %>% mutate(method='VF2Verse')

nf_vif_data = get_TP_FP_per_virus("data/nf_vif.agg.tsv.prepped.truthset_mapped") %>% mutate(method='nf_vif')

```



```{r}

data = bind_rows(ctat_vif_data,
                 ViFi_data,
                 batvi_data,
                 virusbreakend_data,
                 VF2Verse_data,
                 nf_vif_data)

```

# examine TPs

```{r}

data %>% ggplot(aes(x=min_reads, y=TP, fill=virus)) + geom_col(position='dodge') + facet_wrap(~method) + ggtitle("TP")

```


```{r}
# TPs
data %>% ggplot(aes(x=min_reads, y=TP, fill=method)) + geom_col(position='dodge') + facet_wrap(~virus) + ggtitle("TP")

```

# Examine FPs

```{r}

data %>% ggplot(aes(x=min_reads, y=FP, fill=virus)) + geom_col(position='dodge') + facet_wrap(~method) + ggtitle("FP") +
  xlim(c(2,NA)) + ylim(0,10)

```



```{r}
# TPs
data %>% ggplot(aes(x=min_reads, y=FP, fill=method)) + geom_col(position='dodge') + facet_wrap(~virus) + ggtitle("FP") + 
 xlim(c(2,NA)) + ylim(0,10)
  
```


```{r}

MIN_READS = 5

data %>% filter(min_reads == MIN_READS) %>%
  gather(key=scoreType, value=scoreVal, TP, FP) %>%
  ggplot(aes(x=method, y=scoreVal, fill=scoreType)) + geom_col() +
  facet_wrap(~virus) + theme(axis.text.x = element_text(angle = 90, hjust = 1))


```



```{r}

data = data %>%  mutate(FP = ifelse(is.na(FP), 0, FP)) %>%
  mutate(recall = TP / 50 * 100) %>%
  mutate(precision = TP / (TP + FP) * 100) %>%
  mutate(F1 = (2 * precision * recall)  / (precision + recall)) 



```


```{r}

data %>% ggplot(aes(x=method, y=recall, fill=method)) + geom_col() + facet_wrap(~virus) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Recall")


```
```{r}

data %>% ggplot(aes(x=method, y=precision, fill=method)) + geom_col() + facet_wrap(~virus) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Precision")


```

```{r}

data %>% ggplot(aes(x=method, y=F1, fill=method)) + geom_col() + facet_wrap(~virus) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("F1")


```


```{r}

data %>% ggplot(aes(x=virus, y=F1, fill=method)) + geom_col(position='dodge') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("F1")


```





