---
title: "Insertions_and_CNVs"
author: "bhaas"
date: '2023-04-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```


```{r}

insertions_and_cnv_data = read.table("TCGA_insertions_and_CNV_within10kb", sep="\t", header=T, stringsAsFactors = F) %>% unique()

```


```{r}


insertions_data = read.table("../InsertionAnalysis/all_insertions_and_virus_content_merged.FILTERED.tsv", 
                             header=T, sep="\t", stringsAsFactors = F)

insertions_data = insertions_data %>% select(sample_id, contig, humanchr, human_coord, total_rpm)


```

```{r}

insertions_and_cnv_data = left_join(insertions_and_cnv_data %>% rename(sample_id = sample, contig=insertion), 
                                         insertions_data %>% select(-humanchr),
                                         by=c('sample_id', 'contig'))

```



```{r}

BINSIZE=1000000

nrow(insertions_and_cnv_data)

insertions_and_cnv_data = insertions_and_cnv_data %>% 
  mutate(bin = paste0(chrom, "^", round(human_coord / BINSIZE))) %>% group_by(sample_id, bin) %>% 
  arrange(desc(total_rpm)) %>% filter(row_number()==1) %>% ungroup()

nrow(insertions_and_cnv_data)

```


```{r}

insertions_and_cnv_data %>% ggplot(aes(x=virus, y=copy_number, color=virus)) + geom_boxplot() + 
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
   theme(legend.position="none")
  

```

## examine random location data:

```{r}

random_loc_data = read.table("TCGA_insertions_and_CNV_within10kb.random_loc", header=T, sep="\t", stringsAsFactors = F)

nrow(random_loc_data)





```

```{r}

random_loc_data = inner_join(random_loc_data %>% rename(sample_id = sample, contig=insertion),
                             insertions_and_cnv_data %>% select(sample_id, contig),
                             by=c('sample_id', 'contig') )

nrow(random_loc_data)

```

```{r}

random_loc_data %>% ggplot(aes(x=virus, y=copy_number, color=virus)) + geom_boxplot() + 
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
   theme(legend.position="none")

```



```{r}

combined_data = bind_rows(insertions_and_cnv_data %>% mutate(type='real'),
                          random_loc_data %>% mutate(type='random_loc'))

```


```{r}

combined_data %>% ggplot(aes(x=virus, y=copy_number, fill=type)) + geom_boxplot() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_y_continuous(trans='log10')  +
  geom_hline(yintercept=2, linetype=2, color='purple')

```


```{r}
# run statistics

viruses = combined_data %>% select(virus) %>% unique() %>% pull(virus)

stats_df = NULL

for (virus_name in viruses) {
  
  virus_data = combined_data %>% filter(virus == virus_name)
  real_insertions_cnv = virus_data %>% filter(type=='real') %>% pull(copy_number)
  random_loc_cnv = virus_data %>% filter(type=='random_loc') %>% pull(copy_number)
  
  w = wilcox.test(real_insertions_cnv, random_loc_cnv, alternative='greater')
 
  #message(virus_name)
  #print(w)
  
  stats_df = bind_rows(stats_df, data.frame(virus=virus_name, p_raw = w$p.value))
  
}

stats_df$p_bh = p.adjust(stats_df$p, method='hochberg')

stats_df %>% arrange(p_bh)

```