---
title: "Combinerd VIF analysis"
author: "bhaas"
date: '2023-01-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# aggregate virus content data

## TCGA

```{r}

# TCGA RNA-seq results for virus content
TCGA_rnaseq_virus_content = read.table("../TCGA_VIF_analysis/virus_content.tsv", header=T, sep="\t", stringsAsFactors = F)

TCGA_rnaseq_virus_content$participant = str_replace(TCGA_rnaseq_virus_content$sample_name, "-[^\\-]+$", "")
TCGA_rnaseq_virus_content = TCGA_rnaseq_virus_content %>% rename(project=TCGA) %>% mutate(cohort="TCGA")

tcga_study_abbreviations = read.table("../TCGA_VIF_analysis/data/TCGA_study_abbreviations.txt", header=F, sep="\t", stringsAsFactors = F)
colnames(tcga_study_abbreviations) = c('project', 'tissue')

TCGA_rnaseq_virus_content = left_join(TCGA_rnaseq_virus_content, tcga_study_abbreviations, by='project')
TCGA_rnaseq_virus_content = TCGA_rnaseq_virus_content  %>% mutate(seqtype = "RNA")  %>% 
  mutate(tumor_or_normal = ifelse(grepl("^N", sample_type), "normal", "tumor") ) %>%
  select(-sample_type)

```


```{r}
# TCGA WGS results for virus content

TCGA_wgs_virus_content = read.table("../TCGA_VIF_analysis/TCGA_WGS_Analysis/virus_content.tsv", header=T, sep="\t", stringsAsFactors = F)
TCGA_wgs_virus_content$participant = str_replace(TCGA_wgs_virus_content$sample_name, "-[^\\-]+$", "")
TCGA_wgs_virus_content = TCGA_wgs_virus_content %>% rename(project=TCGA) %>% mutate(cohort="TCGA")
TCGA_wgs_virus_content = left_join(TCGA_wgs_virus_content, tcga_study_abbreviations, by='project')
TCGA_wgs_virus_content = TCGA_wgs_virus_content  %>% mutate(seqtype = "WGS")  %>% 
  mutate(tumor_or_normal = ifelse(grepl("-N[^\\-]+$", sample_name), "normal", "tumor") ) 
```


```{r}
# TCGA WXS results for virus content

TCGA_wXs_virus_content = read.table("../TCGA_VIF_analysis/TCGA_WXS_Analysis/virus_content.tsv", header=T, sep="\t", stringsAsFactors = F)
TCGA_wXs_virus_content$participant = str_replace(TCGA_wXs_virus_content$sample_name, "-[^\\-]+$", "")
TCGA_wXs_virus_content = TCGA_wXs_virus_content %>% rename(project=TCGA) %>% mutate(cohort="TCGA")
TCGA_wXs_virus_content = left_join(TCGA_wXs_virus_content, tcga_study_abbreviations, by='project')
TCGA_wXs_virus_content = TCGA_wXs_virus_content  %>% mutate(seqtype = "WXS")  %>% 
  mutate(tumor_or_normal = ifelse(grepl("-N[^\\-]+$", sample_name), "normal", "tumor") ) %>%  
  select(-sample_type)
```


```{r}

TCGA_combined_virus_content = bind_rows(TCGA_rnaseq_virus_content,
                                        TCGA_wgs_virus_content,
                                        TCGA_wXs_virus_content
                                        )

```


## TARGET pediatric 

```{r}

TARGET_rnaseq_virus_content = read.table("../TARGETdb_VIF_analysis/virus_content.tsv", header=T, sep="\t", stringsAsFactors = F)

TARGET_rnaseq_virus_content = TARGET_rnaseq_virus_content %>% mutate(cohort='TARGET', seqtype='RNA') %>%
  mutate(tumor_or_normal = ifelse(grepl("tumor", project), "tumor", "normal")) %>%
  rename(tissue=sample_type)

```

## GTEx

```{r}

GTEx_rnaseq_virus_content = read.table("../GTEx_VIF_analysis/virus_content.tsv", header=T, sep="\t", stringsAsFactors = F)
GTEx_rnaseq_virus_content$participant = sapply(GTEx_rnaseq_virus_content$sample_name, function(x) { str_split(x, "-")[[1]][2]})
GTEx_rnaseq_virus_content = GTEx_rnaseq_virus_content %>% 
  mutate(cohort='GTEx', seqtype='RNA', project=tissue_id, tumor_or_normal='normal') %>% 
  rename(tissue = tissue_id)

```

## CCLE

```{r}

# CCLE rna-seq virus content
CCLE_rnaseq_virus_content = read.table("../CCLE_VIF_analysis/virus_content.tsv", header=T, sep="\t", stringsAsFactors = F) 
  
CCLE_rnaseq_virus_content = CCLE_rnaseq_virus_content %>% 
  mutate(participant=sample_name, seqtype='RNA', cohort='CCLE', project='CCLE', tumor_or_normal='tumor_cell_line') %>%
  rename(tissue=tissue_id)

CCLE_rnaseq_virus_content$sample_name =  sapply(CCLE_rnaseq_virus_content$sample_name, function(x) {str_split(x, "_")[[1]][1] })

```



```{r}
# CCLE WXS

CCLE_wXs_virus_content = read.table("../CCLE_VIF_analysis/CCLE_WXS_analysis/virus_content.tsv", 
                                    header=T, sep="\t", stringsAsFactors = F)

CCLE_wXs_virus_content = CCLE_wXs_virus_content %>% 
  mutate(participant=sample_name, seqtype='WXS', cohort='CCLE', project='CCLE', tumor_or_normal='tumor_cell_line') %>%
  select(-bundled_sample_name) %>%
  rename(tissue=tissue_id)

CCLE_wXs_virus_content$sample_name =  sapply(CCLE_wXs_virus_content$sample_name, function(x) {str_split(x, "_")[[1]][1] })

```

```{r}
# combine CCLE virus content data

CCLE_combined = bind_rows(CCLE_rnaseq_virus_content,
                          CCLE_wXs_virus_content)

CCLE_combined = CCLE_combined %>% mutate(sample_name = ifelse(sample_name == "TT", participant, sample_name))
```



## Nat Genetics 2015 hyb capture

```{r}

NATGEN2015_hybcap_virus_content = read.table("../NatGenetics2015_reanalysis/NatGenetics2015_VIF/virus_content.tsv", 
                                             header=T, sep="\t", stringsAsFactors = F)

NATGEN2015_hybcap_virus_content = NATGEN2015_hybcap_virus_content %>% 
  rename(seqtype = sample_type) %>%
  mutate(cohort="NATGEN2015") %>% 
  mutate(project="NATGEN2015") %>%
  mutate(tumor_or_normal = "tumor") %>%
  mutate(tissue = "cervical", sample_type = "cervical") %>%
  mutate(seqtype = ifelse(seqtype == 'hivid', 'HYB', seqtype)) %>%
  mutate(seqtype = ifelse(seqtype == 'rnaseq', 'RNA', seqtype)) %>%
  mutate(seqtype = ifelse(seqtype == 'wgs', 'WGS', seqtype)) %>%
  mutate(participant = sample_label_short) %>% 
  select(-sra_num_reads, -sample_label, -sample_label_short)


NATGEN2015_hybcap_virus_content = NATGEN2015_hybcap_virus_content %>% 
  mutate(tumor_or_normal = ifelse(participant %in% c('CASKID', 'S12', 'SIHA', 'HELA'), "tumor_cell_line", tumor_or_normal))

  
```

## Combine all
```{r}

combined_all_virus_content = bind_rows(TCGA_combined_virus_content,
                                       TARGET_rnaseq_virus_content,
                                       GTEx_rnaseq_virus_content,
                                       CCLE_combined,
                                       NATGEN2015_hybcap_virus_content)

```

```{r}

combined_all_virus_content$tissue = str_replace_all(combined_all_virus_content$tissue, " ", "_")


```


```{r}

# rename common viruses and deal with EBV strain issue


combined_all_virus_content = combined_all_virus_content %>% 
  mutate(virus = ifelse(virus=="NC_007605_171823nt_Human_gammaherpesvirus_4" | virus == "NC_009334_172764nt_Human_herpesvirus_4_type_2", "Eppstein-Barr", virus)) %>%
                                         mutate(virus = ifelse(virus=="NC_003977_3182nt_Hepatitis_B_virus", "HBV", virus))

nrow(combined_all_virus_content)


```


```{r}

# sum content across EBV strains since only primary alignments were considered.

EBV_virus_content = combined_all_virus_content %>% filter(virus == "Eppstein-Barr")
nrow(EBV_virus_content)

EBV_virus_content = EBV_virus_content %>%
  group_by(sample_name, seqtype) %>% 
  mutate(sum_mapped = sum(mapped), 
  max_n_bases_covered = max(n_bases_covered), 
  max_frac_covered = max(frac_covered) ) %>% 
  arrange(desc(chim_reads)) %>% filter(row_number()==1) %>%
  ungroup() %>%
  mutate(mapped = sum_mapped, n_bases_covered = max_n_bases_covered, frac_covered = max(frac_covered),
         mapped_rpm = sum_mapped / sample_read_count * 1e6) %>%
  select(-sum_mapped, -max_n_bases_covered, -max_frac_covered)

nrow(EBV_virus_content)                                                
```






```{r}

# remake combined_all_virus_content substituting the revised EBV content info

combined_all_virus_content = bind_rows(combined_all_virus_content %>% filter(virus != "Eppstein-Barr"),
                                       EBV_virus_content)
  
  
nrow(combined_all_virus_content)

```


```{r}

combined_all_virus_content = combined_all_virus_content %>%
  mutate(sample_id = sample_name) %>%
  mutate(sample_name = paste(participant, tumor_or_normal, sep="^"))
  

```


```{r}

write.table(combined_all_virus_content, file="virus_content_unfiltered.tsv", sep="\t", quote=F, row.names=F)
```






