---
title: "AnalyzeHotspots"
author: "bhaas"
date: '2023-03-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```



```{r}

hotspot_info = read.table("plot.hotspots.win_5e5.tsv.w_20_neighbors.hotspot_virus_sample_counts.tsv", header=T, sep="\t", stringsAsFactors = F)

head(hotspot_info)

```

```{r}

hotspot_info %>% select(hotspot) %>% unique() %>% nrow()

```

```{r}

hotspot_sum_sample_virus_counts = hotspot_info %>% select(hotspot_name, virus_genome, hotspot_virus_tally) %>% group_by(hotspot_name) %>% summarize(sum_sample_viruses = sum(hotspot_virus_tally)) %>% arrange(desc(sum_sample_viruses)) %>% ungroup()

hotspot_sum_sample_virus_counts

```


```{r}

hotspot_sum_sample_virus_counts %>% ggplot(aes(x=reorder(hotspot_name, -1*sum_sample_viruses), sum_sample_viruses)) + geom_col() +
  ggtitle("sum(virus,sample) ranked hotspots")


```

```{r}

hotspot_sum_sample_virus_counts  %>% group_by(sum_sample_viruses) %>% tally()


```

```{r}

hotspot_sum_sample_virus_counts  %>% group_by(sum_sample_viruses) %>% tally() %>%
  ggplot(aes(x=as.factor(sum_sample_viruses), y=n)) + geom_col() +
  ggtitle("Number of hotspots with number of sample/viruses at sites") +
  xlab("number of sample/viruses at site") + ylab("number of hotspots")

```


```{r}


top_hotspots = hotspot_info %>% group_by(hotspot_name) %>% summarize(sum_insertions = sum(hotspot_virus_tally)) %>% ungroup()

top_hotspots %>% arrange(desc(sum_insertions))


```



```{r}

 hotspot_info =  left_join(hotspot_info, top_hotspots, by='hotspot_name')

```


```{r}

hotspot_info %>% filter(sum_insertions >= 10) %>% 
  ggplot(aes(x=reorder(hotspot_name, -1*sum_insertions), y=hotspot_virus_tally, fill=virus_genome)) + geom_col() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1))
  


```



```{r}

hotspot_info %>% filter(sum_insertions >= 5) %>% 
  mutate(virus_genome = ifelse(grepl("HPV", virus_genome), "HPV", virus_genome)) %>%
  ggplot(aes(x=reorder(hotspot_name, -1*sum_insertions), y=hotspot_virus_tally, fill=virus_genome)) + geom_col() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1))
  

```

```{r}
hotspot_info %>% filter(sum_insertions >= 8) %>% 
  mutate(virus_genome = ifelse(grepl("HPV", virus_genome), "HPV", virus_genome)) %>%
  ggplot(aes(x=reorder(hotspot_name, -1*sum_insertions), y=hotspot_virus_tally, fill=virus_genome)) + geom_col() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


  

