---
title: "Counting Orthogonal Validations"
author: "bhaas"
date: '2023-03-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```



```{r}

filtered_insertions_data = read.table("all_insertions_and_virus_content_merged.w_shared_site_info.tsv", header=T, sep="\t", stringsAsFactors = F) %>%
  filter(matching_virus_content)

nrow(filtered_insertions_data)
```



```{r}

samples_in_rnaseq_and_other_seqtype = intersect(filtered_insertions_data %>% filter(seqtype == "RNA") %>% select(sample_name) %>% unique() %>% pull(sample_name),
                                               filtered_insertions_data %>% filter(seqtype != "RNA") %>% select(sample_name) %>% unique() %>% pull(sample_name) )


samples_in_rnaseq_and_other_seqtype 

length(samples_in_rnaseq_and_other_seqtype )

```


```{r}

# restrict insertions to those in matched samples

nrow(filtered_insertions_data)

filtered_insertions_data = filtered_insertions_data %>% filter(sample_name %in% samples_in_rnaseq_and_other_seqtype) 

nrow(filtered_insertions_data)
```



# What fraction of insertion loci are actually shared between sample seqtypes?

```{r}

BINSIZE=10000

filtered_insertions_data = filtered_insertions_data %>% 
  mutate(coord_bin = round(human_coord / BINSIZE) * BINSIZE ) %>% 
  mutate(insertion_locus = paste0(humanchr, "^", coord_bin)) %>% 
  select(-coord_bin)


```

```{r}

# restrict insertion loci to rna-seq having matched samples

nrow( filtered_insertions_data)

insertion_loci = filtered_insertions_data %>% select(sample_name, insertion_locus, virus, seqtype, cohort) %>% unique()

# distilled from insertion sites to loci
nrow(insertion_loci)

# examine counts of insertion loci by cohort and seqtype
insertion_loci %>% group_by(seqtype, cohort) %>% tally()

```

```{r}

matching_insertions = read.table("rna_insertions_within_10kb_other_seqtype_insertions.tsv", header=T, sep="\t", stringsAsFactors = F) 
  
matching_insertions = matching_insertions %>%

  mutate(rna_coord_bin = round(rna_human_coord / BINSIZE) * BINSIZE) %>%
  mutate(rna_insertion_locus = paste0(rna_humanchr, "^", rna_coord_bin)) %>%  
  
  mutate(other_coord_bin = round(human_coord / BINSIZE) * BINSIZE ) %>% 
  mutate(other_insertion_locus = paste0(humanchr, "^", other_coord_bin)) %>% 
  
  select(-rna_coord_bin, -other_coord_bin)

matching_insertions = matching_insertions %>% filter(within_range) %>% select(sample_name, virus, rna_insertion_locus, seqtype, other_insertion_locus, cohort) %>% unique()


matching_insertions

message("number of matched rna insertion loci: ", nrow(matching_insertions %>% select(rna_insertion_locus) %>% unique()))

matching_insertions %>% select(other_insertion_locus, seqtype, cohort) %>% unique() %>% group_by(seqtype, cohort) %>% tally() 

```

```{r}

# identify the evidence for rna-seq validated insertions to include as main table attribute

matching_insertions_report = matching_insertions %>% select(sample_name, virus, rna_insertion_locus, seqtype, cohort) %>% 
  unique() %>%
  group_by(sample_name, virus, rna_insertion_locus, cohort) %>%
   arrange(seqtype) %>%
  mutate(ortho_validation = paste(seqtype, collapse=",")) %>% select(-seqtype) %>% unique()

matching_insertions_report

write.table(matching_insertions_report, file="rnaseq_insertions.orthovalidations.tsv", sep="\t", quote=F, row.names=F)

```



```{r}

all_matching_insertion_loci = bind_rows(
  # rna-seq insertions
                         matching_insertions %>% select(sample_name, virus, insertion_locus = rna_insertion_locus, cohort) %>% 
                                          mutate( seqtype="RNA") %>% unique(),
  # other insertions                                      
                        matching_insertions %>%
                                        select(sample_name, virus, insertion_locus = other_insertion_locus, seqtype, cohort) ) %>%
                                        unique()
                                      


nrow(all_matching_insertion_loci)

all_matching_insertion_loci %>% group_by(seqtype, cohort) %>% tally()

```

```{r}

insertion_loci_valid_label = left_join(insertion_loci,
                             all_matching_insertion_loci %>% mutate(locus_orthogonally_validated = TRUE),
                             by=c('sample_name' ,'virus', 'insertion_locus', 'seqtype', 'cohort') ) %>% 
  mutate(locus_orthogonally_validated = ifelse(is.na(locus_orthogonally_validated), FALSE, locus_orthogonally_validated))

nrow(insertion_loci_valid_label)

```


```{r}
# general stats on overall counts and proportions of validated insertion loci

num_insertion_loci_by_seqtype = insertion_loci_valid_label  %>%  group_by(seqtype, cohort) %>% tally(name='num_insertion_loci')

num_orthog_valid_by_seqtype = insertion_loci_valid_label  %>%  filter(locus_orthogonally_validated) %>% 
  group_by(seqtype, cohort) %>% tally(name='valid_insertion_loci')

orthog_valid_insertion_loci_stats = full_join(num_insertion_loci_by_seqtype,
                                              num_orthog_valid_by_seqtype,
                                              by=c('seqtype', 'cohort'))

orthog_valid_insertion_loci_stats = orthog_valid_insertion_loci_stats %>% mutate(frac_loci_valid = valid_insertion_loci / num_insertion_loci)

orthog_valid_insertion_loci_stats

```



```{r}

# examine fraction validated per sample

insertion_loci_valid_label %>% group_by(sample_name, virus, seqtype, cohort, locus_orthogonally_validated) %>% tally() %>% mutate(pct=prop.table(n))


```



```{r}

insertion_loci_valid_label_fracs = insertion_loci_valid_label %>%
  group_by(sample_name, virus, seqtype, cohort,  locus_orthogonally_validated) %>% tally() %>% mutate(pct=prop.table(n)) %>% ungroup()

insertion_loci_valid_label_fracs 

```

```{r}
insertion_loci_valid_label_fracs_spread = full_join(insertion_loci_valid_label_fracs %>% filter(locus_orthogonally_validated) %>% select(-locus_orthogonally_validated),
          insertion_loci_valid_label_fracs %>% filter(! locus_orthogonally_validated) %>% select(-locus_orthogonally_validated),
          by=c('sample_name', 'virus', 'seqtype', 'cohort'), 
          suffix=c('.true', '.false'))

insertion_loci_valid_label_fracs_spread[is.na(insertion_loci_valid_label_fracs_spread )] = 0

insertion_loci_valid_label_fracs_spread
```

```{r}

insertion_loci_valid_label_fracs_spread %>% 
  filter(cohort == "TCGA") %>%
  mutate(n.total = n.true + n.false) %>%
    ggplot(aes(x=n.total, y=pct.true, color=virus)) + 
  #geom_point(alpha=0.9) + 
  geom_jitter(height=0.02, width=0.02) +
  facet_wrap(~seqtype, scale='free') +
  ggtitle("TCGA - fraction insertions ortho-validated by sample")

```



```{r}

insertion_loci_valid_label_fracs_spread %>% 
  filter(cohort == "NATGEN2015") %>%
  mutate(n.total = n.true + n.false) %>%
    ggplot(aes(x=n.total, y=pct.true, color=virus)) + 
  #geom_point(alpha=0.9) + 
  geom_jitter(height=0.02, width=0.02) +
  facet_wrap(~seqtype, scale='free') +
  ggtitle("NATGEN2015 - fraction insertions ortho-validated by sample")

```

```{r}
insertion_loci_valid_label_fracs_spread %>% filter(cohort=="TCGA") %>%
  mutate(n.total = n.true + n.false) %>%
    ggplot(aes(x=as.factor(n.total), y=pct.true, color=virus)) + geom_boxplot() + facet_wrap(~seqtype, scale='free', ncol=1) +
  ggtitle("TCGA - frac insertions ortho-validated per sample by total insertion count")

```



```{r}
insertion_loci_valid_label_fracs_spread %>% filter(cohort=="NATGEN2015") %>%
  mutate(n.total = n.true + n.false) %>%
    ggplot(aes(x=as.factor(n.total), y=pct.true, color=virus)) + geom_boxplot() + facet_wrap(~seqtype, scale='free', ncol=1) +
  ggtitle("NATGEN2015 - frac insertions ortho0-validated per sample by total insertion count")

```



```{r}
insertion_loci_valid_label_fracs_spread %>% 
  mutate(n.total = n.true + n.false) %>%
    ggplot(aes(x=as.factor(n.total), y=pct.true, color=virus)) + geom_boxplot() + facet_wrap(~seqtype, scale='free', ncol=1) +
  ggtitle("Frac insertions ortho-validated per sample by total insertion count")

```


