---
title: "FHIT_hotspot_insertions.Rmd"
author: "bhaas"
date: '2023-04-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(useful)
```


```{r}

hotspot_insertions = read.table("hotspots.win_1e5.tsv.w_20_neighbors", header=T, sep="\t", stringsAsFactors = F)

```


```{r}

FHIT_insertions = hotspot_insertions %>% filter(insert_genes == "FHIT")

```


```{r}

FHIT_insertions %>% select(sample, sample_id, is_primary, seqtype, virus, human_coord, virus_coord, total, total_rpm)


```


```{r}

FHIT_insertion_matrix = FHIT_insertions %>% mutate(insertion_coord = paste0(virus, ":", virus_coord, "^", human_coord)) %>%
  select(sample, insertion_coord, total_rpm) %>% spread(key=sample, value=total_rpm)


corner(FHIT_insertion_matrix)
```
```{r}

#FHIT_insertion_matrix[is.na(FHIT_insertion_matrix)] = 0

rownames(FHIT_insertion_matrix) = FHIT_insertion_matrix[,1]

FHIT_insertion_matrix = FHIT_insertion_matrix[,-c(1)]

FHIT_insertion_matrix = as.matrix(FHIT_insertion_matrix)

```

```{r}
library(pheatmap)

m = as.matrix(log2(FHIT_insertion_matrix+1))
m_for_dist = m
m_for_dist[is.na(m)] = 0

hotspot_dists = dist(m_for_dist)
hotspot_clust = hclust(hotspot_dists)

sample_dists = dist(t(m_for_dist))
sample_clust = hclust(sample_dists)

pheatmap(m, na_col = "gray", cluster_rows=hotspot_clust, cluster_cols=sample_clust)


```






