---
title: "SamplesMultHotspotsRepresented"
author: "bhaas"
date: '2023-05-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
data = read.table("../DecorateInsertions/all_insertions_and_virus_content_merged.FILTERED.Decorated.tsv", header=T, sep="\t", stringsAsFactors=F)

```


```{r}

sample_hotspots_ge11 = data %>% filter(hotspot_participant_count >= 11) %>% select(sample_id, hotspot, virus) %>% unique()

head(sample_hotspots_ge11)


```


```{r}
sample_mult_hotspots_ge11 = sample_hotspots_ge11 %>% select(sample_id, hotspot) %>% unique() %>% group_by(sample_id) %>% tally(name='num_hotspots_ge11') %>% filter(num_hotspots_ge11 > 1)

head(sample_mult_hotspots_ge11 %>% arrange(desc(num_hotspots_ge11)))

```

```{r}
#  how many samples have multiple ge11 hotspots represented?

nrow(sample_mult_hotspots_ge11)


```

```{r}

left_join(sample_mult_hotspots_ge11, sample_hotspots_ge11, by='sample_id') %>% arrange(desc(num_hotspots_ge11))

```

# some interesting examples with additional effects.


```{r}
inner_join(sample_mult_hotspots_ge11, 
           data %>% select(sample_id, fusions_at_insertion,  spliced_gene) %>% filter(! (is.na(fusions_at_insertion) & is.na(spliced_gene))) %>% unique(), 
           by='sample_id') %>% arrange(desc(num_hotspots_ge11), sample_id)
```





