---
title: "HotspotVirusCancerRepresentation"
author: "bhaas"
date: '2023-06-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
```


# parse inputs

```{r}

all_samples_processed = read.table("../all_samples_processed.tsv", header=T, sep="\t", stringsAsFactors = F)

```


```{r}

all_insertions_data = read.table("../DecorateInsertions/all_insertions_and_virus_content_merged.FILTERED.Decorated.tsv", header=T, sep="\t", stringsAsFactors = F)

# rename all HPV strains as HPV
all_insertions_data = all_insertions_data %>% mutate(virus = ifelse(grepl("HPV", virus), "HPV", virus))

```



# analysis


```{r}

# count samples by project and tumor/normal type

all_sample_counts = all_samples_processed %>% select(project, tumor_or_normal, participant) %>% 
  unique() %>% 
  group_by(project, tumor_or_normal) %>%
  tally(name='project_sample_count')

all_sample_counts

```

```{r}
# count participant hotspots

MIN_HOTSPOT_PARTICIPANTS = 9

all_project_hotspot_counts = all_insertions_data %>%
  filter(hotspot_participant_count >= MIN_HOTSPOT_PARTICIPANTS) %>%
  select(project, tumor_or_normal, hotspot, virus, participant) %>% unique() %>%
  group_by(project, tumor_or_normal, hotspot, virus) %>% tally(name='project_hotspot_count')

all_project_hotspot_counts %>% arrange(desc(project_hotspot_count))

```

```{r}

all_project_hotspot_counts = left_join(all_project_hotspot_counts, all_sample_counts,
                                       by=c('project', 'tumor_or_normal'),
                                       multiple='all')

all_project_hotspot_counts %>% arrange(desc(project_hotspot_count))
```

```{r}

# get fractional representation

all_project_hotspot_counts = all_project_hotspot_counts %>% mutate(frac_samples = project_hotspot_count / project_sample_count)


```

# Cervical cancer

```{r}

# compare CESC to NATGEN2015

cesc_hotspot_counts = all_project_hotspot_counts %>% filter(project=="CESC") %>% 
  select(hotspot, tumor_or_normal, frac_samples, project_hotspot_count, project_sample_count)

natgen2015_hotspot_counts = all_project_hotspot_counts %>% 
  filter(project=="NATGEN2015") %>% 
  select(hotspot, tumor_or_normal, frac_samples, project_hotspot_count, project_sample_count) %>%
  filter(tumor_or_normal %in% c('tumor', 'normal'))

cesc_vs_natgen_counts = full_join(cesc_hotspot_counts, natgen2015_hotspot_counts,
                                   by=c('hotspot', 'tumor_or_normal'),
                                   suffix=c('.cesc', '.natgen2015'))

cesc_vs_natgen_counts = cesc_vs_natgen_counts %>% 
  mutate(frac_samples.cesc = ifelse(is.na(frac_samples.cesc), 0, frac_samples.cesc)) %>%
  mutate(frac_samples.natgen2015 = ifelse(is.na(frac_samples.natgen2015), 0, frac_samples.natgen2015))

```


```{r}

data_filt =  cesc_vs_natgen_counts %>% filter(frac_samples.cesc > 0.025 | frac_samples.natgen2015 > 0.1)

cesc_vs_natgen_counts %>% ggplot(aes(x=frac_samples.cesc, y=frac_samples.natgen2015)) + geom_point() +
    theme_bw() +
  geom_point(data=data_filt, color='purple') +
  geom_text_repel(data = data_filt, aes(label=hotspot))  +
  geom_abline(slope=1, color='orange') + 
  ggtitle("CESC vs. NATGEN2015 Cerivical Cancer HPV Hotspot Prevalence")
```


```{r}

cesc_vs_natgen_counts %>% filter(frac_samples.cesc > 0.025 | frac_samples.natgen2015 > 0.1) %>% arrange(desc(frac_samples.cesc))

```

```{r}

# get an aggregate view of hotspot prevalence

cesc_vs_natgen_counts = cesc_vs_natgen_counts %>% 
  mutate(project_hotspot_count.combined = project_hotspot_count.cesc + project_hotspot_count.natgen2015) %>%
  mutate(project_sample_count.combined = project_sample_count.cesc + project_sample_count.natgen2015) %>%
  mutate(frac_samples.combined = project_hotspot_count.combined / project_sample_count.combined)

cesc_vs_natgen_counts %>% select(hotspot, frac_samples.combined, frac_samples.cesc, frac_samples.natgen2015) %>% arrange(desc(frac_samples.combined))


# chr13:73369712^LINC00393 consistently found at 4% in both CESC and NatGen2015

```


```{r}

hpv_cervical_hotspot_stats = cesc_vs_natgen_counts %>% 
  filter(frac_samples.combined >= 0.01) %>%
  rowwise() %>% mutate(lowval=min(frac_samples.cesc, frac_samples.natgen2015), highval=max(frac_samples.cesc, frac_samples.natgen2015)) 

hpv_cervical_hotspot_stats %>% ungroup() %>% arrange(desc(frac_samples.combined)) %>% select(hotspot, frac_samples.cesc, frac_samples.natgen2015, frac_samples.combined)

hpv_cervical_hotspot_stats %>% 
  ggplot(aes(x=reorder(hotspot, -1*frac_samples.combined), y=frac_samples.combined)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_errorbar(aes(x=hotspot, ymin = lowval,
                                ymax = highval), color='red')


```

Examine the chr8 aggregate hotspot

```{r}

cesc_hotspot_counts %>% filter(grepl("chr8:", hotspot))

```

```{r}

# just CESC 

chr8_larger_hotspot =  c('chr8:127252151^CASC8', 'chr8:127649782^CASC11', 'chr8:127765602^PVT1')

all_insertions_data %>% filter(project=="CESC" & tumor_or_normal == "tumor") %>%
  filter(hotspot %in% chr8_larger_hotspot) %>%
  select(participant, virus) %>% unique() 


```

40/307 = 13%


```{r}
# just NATGEN

all_insertions_data %>% filter(project=="NATGEN2015" & tumor_or_normal == "tumor") %>% select(participant) %>% unique() %>% nrow()

all_insertions_data %>% filter(project=="NATGEN2015" & tumor_or_normal == "tumor") %>%
  filter(hotspot %in% chr8_larger_hotspot) %>%
  select(participant, virus) %>% unique() 


```

13/122=11%


# HBV

```{r}

all_project_hotspot_counts %>% filter(virus == "HBV") %>% 
  filter(tumor_or_normal %in% c('tumor', 'normal')) %>%
  filter(project_hotspot_count > 1) %>%
  ggplot(aes(x=reorder(hotspot, -1*frac_samples), y=frac_samples, fill=tumor_or_normal, color=project)) + 
  geom_bar(stat='identity', position='dodge') +
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("HBV Hotspot prevalence")


```

```{r}

all_project_hotspot_counts %>% filter(virus == "HBV") %>% 
  filter(tumor_or_normal %in% c('tumor', 'normal')) %>%
  filter(project_hotspot_count > 1) %>% arrange(desc(frac_samples))

# HBV and TERT = 5% of LIHC tumor samples
# HBV and KMT2B: 3% of LIHC tumor samples

# HBV and FN1: 4$ of LIHC matched normal samples

```








# EBV

```{r}

all_project_hotspot_counts %>% 
  filter(virus == "EBV") %>% 
  filter(tumor_or_normal %in% c('tumor', 'normal')) %>%
  filter(project_hotspot_count > 1 & frac_samples >= 0.05) %>%
  ggplot(aes(x=reorder(hotspot, -1*frac_samples), y=frac_samples, fill=tumor_or_normal, color=project)) + 
  geom_bar(stat='identity', position='dodge') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("EBV Hotspot prevalence")



```

```{r}

all_insertions_data %>% filter(virus == "EBV") %>% select(project, cohort, participant) %>% unique() %>% 
  group_by(project, cohort) %>% tally() %>% ungroup() %>% mutate(frac=prop.table(n))
```

83% of participants with EBV insertions derive from GTEx/EBV-transformed lymphocytes.

```{r}

all_insertions_data %>% filter(virus == "EBV") %>% 
  group_by(project, cohort) %>% tally() %>% ungroup() %>% mutate(frac=prop.table(n))
```
94% of EBV insertions derive from GTEx/EBV-transformed lymphocytes.





