---
title: "SamplesMultHotspotsRepresented"
author: "bhaas"
date: '2023-05-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
data = read.table("../DecorateInsertions/all_insertions_and_virus_content_merged.FILTERED.Decorated.tsv", header=T, sep="\t", stringsAsFactors=F)

```


```{r}


MIN_HOTSPOT_PARTICIPANTS = 9

sample_hotspots_multi = data %>% filter(hotspot_participant_count >= MIN_HOTSPOT_PARTICIPANTS) %>% select(sample_id, hotspot, virus) %>% unique()

head(sample_hotspots_multi)


```


```{r}
sample_mult_hotspots_multi = sample_hotspots_multi %>% select(sample_id, hotspot) %>% unique() %>% group_by(sample_id) %>% tally(name='num_hotspots_multi') %>% filter(num_hotspots_multi > 1)

head(sample_mult_hotspots_multi %>% arrange(desc(num_hotspots_multi)))

```

```{r}
#  how many samples have multiple hotspots represented?

nrow(sample_mult_hotspots_multi)

# 432 samples with multiple hotspots represented

```

```{r}

left_join(sample_mult_hotspots_multi, sample_hotspots_multi, by='sample_id') %>% arrange(desc(num_hotspots_multi))

```


```{r}

sample_hotspots_multi %>% filter(sample_id == "SRR1611094") %>% select(hotspot, virus) %>% unique() %>% group_by(virus) %>% tally()

# have 127 HPV33 insertions at hotspots in SRR1611095

```

```{r}
sample_hotspots_multi %>% filter(sample_id == "VCAP") %>% select(hotspot, virus) %>% unique() %>% group_by(virus) %>% tally()


# 68 Murine type C retrovirus insertions at hotspots in VCAP

```


```{r}

 
sample_hotspots_multi %>% filter(sample_id == "GTEX-1F5PK-0001-SM-EVR37") %>% select(hotspot, virus) %>% unique() %>% group_by(virus) %>% tally()


# 52 EBV insertions at hotspots in GTEx sample: GTEX-1F5PK-0001-SM-EVR37

```

# some interesting examples with additional effects.


```{r}
inner_join(sample_mult_hotspots_multi, 
           data %>% select(sample_id, fusions_at_insertion,  spliced_gene) %>% filter(! (is.na(fusions_at_insertion) & is.na(spliced_gene))) %>% unique(), 
           by='sample_id') %>% arrange(desc(num_hotspots_multi), sample_id)
```





